version: '3.9'

services:
  app:
    image: ${DOCKER_USERNAME}/devops-app:staging
    container_name: app-staging

    restart: unless-stopped

    ports:
      - "8081:80"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-staging

    restart: unless-stopped

    ports:
      - "9091:9090"

    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml