name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push DEV image
        if: github.ref == 'refs/heads/dev'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:dev ./app
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:dev

      - name: Build and push STAGING image
        if: github.ref == 'refs/heads/staging'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:staging ./app
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:staging

      - name: Build and push PROD image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:prod ./app
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:prod

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Deploy to DEV EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-app:dev
            docker rm -f app-dev || true
            docker run -d -p 8080:80 --name app-dev ${{ secrets.DOCKER_USERNAME }}/devops-app:dev

            echo "Waiting app to start..."
            sleep 5
            curl -f http://localhost:8080 || (echo "Healthcheck FAILED DEV" && exit 1)

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Deploy to STAGING EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-app:staging
            docker rm -f app-staging || true
            docker run -d -p 8081:80 --name app-staging ${{ secrets.DOCKER_USERNAME }}/devops-app:staging

            echo "Waiting app to start..."
            sleep 5
            curl -f http://localhost:8081 || (echo "Healthcheck FAILED STAGING" && exit 1)

  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to PROD EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-app:prod
            docker rm -f app-prod || true
            docker run -d -p 8082:80 --name app-prod ${{ secrets.DOCKER_USERNAME }}/devops-app:prod

            echo "Waiting app to start..."
            sleep 5
            curl -f http://localhost:8082 || (echo "Healthcheck FAILED PROD" && exit 1)
