name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ✅ Build DEV
      - name: Build & Push DEV
        if: github.ref == 'refs/heads/dev'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:dev ./app
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:dev

      # ✅ Build PROD
      - name: Build & Push MAIN
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:main ./app
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:main


  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Deploy ke DEV EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-app:dev
            docker rm -f app-dev || true
            docker run -d -p 80:80 --name app-dev ${{ secrets.DOCKER_USERNAME }}/devops-app:dev


  deploy-main:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy ke MAIN EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-app:main
            docker rm -f app-prod || true
            docker run -d -p 80:80 --name app-prod ${{ secrets.DOCKER_USERNAME }}/devops-app:main